[package]
name = "r-approx"
version = "1.3.0"
authors = ["Roman Bolgov"]
description = "TPK-K thermocompensator"
edition = "2021"
publish = false

[dependencies]
plotters = "=0.3.3"
opener = "0.6"
clap = { version = "4.3", features = ["derive"] }
chrono = "0.4"
regex = "1.8"
