[package]
name = "r-approx"
version = "1.3.2"
authors = ["Roman Bolgov"]
description = "TPK-K thermocompensator"
edition = "2021"
publish = false
rust-version = "1.65"

[dependencies]
plotters = "0.3"
opener = "0.6"
clap = "=3.2"
chrono = "0.4"
regex = "1.10"
