[package]
name = "r-approx"
version = "1.1.0"
authors = ["Roman Bolgov"]
description = "TPK-K thermocompensator"
edition = "2021"
publish = false

[dependencies]
plotters = "0.3"
opener = "0.5"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"
